### ISSUE TITLE
69310.43 becomes 69,931.43

### ISSUE THREAD

**Issue by bbigras** [joiggama/money#1]
``` go
func TestBug(t *testing.T) {
    var input float64 = 69310.43
    expected := "69,310.43"

    if v := New(input, Options{"with_symbol": false}); v != expected {
        t.Errorf("Expected %s to be %s", v, expected)
    }
}
```

```
go test
--- FAIL: TestProb (0.00s)
        money_test.go:133: Expected 69,931.43 to be 69,310.43
FAIL
exit status 1
FAIL    github.com/joiggama/money       0.065s
```

**Comment by joiggama** [comment]
Hi @bbigras thanks for filing the issue, I will take a look as soon as possible.

**Comment by bbigras** [comment]
Your last message was edited 1 hour ago. Was it you or some script? I'm curious since it's an old issue.

**Comment by joiggama** [comment]
> Your last message was edited 1 hour ago. Was it you or some script? I'm curious since it's an old issue.

Ouch, my apologies, wasn't my intention to disturb.  Indeed, I was playing with some api/bash scripting.

**Comment by bbigras** [comment]
hehe no worries. Thanks for the reply.
