### ISSUE TITLE
Issue handling negative values

### ISSUE THREAD

**Issue by juancaacuna** [joiggama/money#3]
Hi! When I convert `-508.65` I get `$-,508..65`

```
money.Format(-508.65, money.Options{"currency": "USD"})
```

Could you please check this? Thanks!

**Comment by joiggama** [comment]
@juancaacuna so, I think I missed this issue... 😓 , I'm not used to people using my open source experiments/toy projects. Thanks for reporting the issue, and apologies for not replying earlier. Hopefully this issue being addressed several years later  makes you laugh a bit. Cheers.
